// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// countSeqFeatureCpp
List countSeqFeatureCpp(CharacterVector RseqDNA, int k);
RcppExport SEXP VirFinder_countSeqFeatureCpp(SEXP RseqDNASEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type RseqDNA(RseqDNASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(countSeqFeatureCpp(RseqDNA, k));
    return rcpp_result_gen;
END_RCPP
}
